
name: Build ophub OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [hg680p, x86_64, b860h_v1, b860h_v2, b860h_v5, opiz3, rpi3, rpi4, rpi5]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib             gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip             zlib1g-dev file wget libelf-dev

      - name: Clone source (ophub)
        run: |
          git clone https://github.com/ophub/amlogic-s9xxx-openwrt openwrt

      - name: Load config from list
        run: |
          awk '/^### DEVICE: ${{ matrix.device }}$/,/^### DEVICE:/' Devices/device_configs.list | grep -v '^###' > openwrt/.config

      - name: Update and install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Fetch DTB
        run: bash scripts/fetch_dtb.sh ${{ matrix.device }} openwrt/files/boot/

      - name: Build firmware
        run: |
          cd openwrt
          make defconfig
          make -j$(nproc)

      - name: Upload firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ matrix.device }}-ophub
          files: openwrt/bin/targets/**/*.img.gz
